### ISSUE TITLE
Is it necessary to use the docker image "node:18.18.2" to successfully execute the scripts ?

### ISSUE THREAD

**Issue by asanson1404** [paltalabs/mercury-client#10]
Hey!

I'm also using Mercury to index smart contract datas. I followed your implementation and, just as you, I used axios. However, I've noticed that we can't successfully request Mercury datas if we don't execute our scripts inside a docker container (image `node:18.18.2`).

Here is the error when I run `node scripts/subscribeToEvent.ts` from my local repo:
![image](https://github.com/paltalabs/mercury-client/assets/95913911/6ef5e4be-997b-4f49-9d75-e3ba5edddd8a)

Is it the same for you? Do you have an idea of why it only works from within the docker container?

Is it possible to suscribe and request Mercury events without using that Docker image?

Thanks for your help!

asanson

**Comment by asanson1404** [comment]
@esteblock @chopan123

**Comment by chopan123** [comment]
Hi! It should work without docker image, however we find that using docker is a way to make sure the code we write will work everywhere.

Can you share the script you are trying to execute? I got that error several times but it was always something I was doing wrong (wrong endpoint, or wrong request)

**Comment by asanson1404** [comment]
Hi @chopan123! Thanks for your reply.

Here is the script I want to execute: https://github.com/asanson1404/smartdeploy-indexer/blob/main/scripts/suscribeDeployEvent.js
(You will notice that this repo is very similar to yours, so will be easy for you to debug).

Running the command `node scripts/suscribeToEvent.ts` inside the Node Docker Container works, but it fails when I run it directly from my computer. Maybe it's my port settings?

Thanks for your help!

**Comment by asanson1404** [comment]
Hey,
Just to let you know that I found the problem. It was missing `require("dotenv").config()` in my script.
Otherwise, the env variables couldn't been read...
