### ISSUE TITLE
Make a subscriptionConfig.json file

### ISSUE THREAD

**Issue by chopan123** [paltalabs/mercury-client#2]
Add a `subscriptionConfig.json`

- [ ] It will have all the contract addresses with its type of subscription (entry and/or event): For this iteration consider:
  - [ ] Router
  - [ ] Factory
  - [ ] Pairs
- [x] Make/modify a `subscribe.js` script that subscribes for all addresses  in `subscriptionConfig,json`, with its type.
- [ ] It should check that the address with its type have not been subscribed before

## Context:
There is 4 types of subscription:
1. Contract events
2. Ledger entries
3. Ledger etries expiration
4. Full account subscriptions - Stellar Classic

Proposed structure: (it could change depending on usage/discoveries)
```json
{
"subscriptions":[{
        "contract": "pair_ARST_AQUA",
        "address": "CAXROB2BP7SIIEHPD52NQKUXFD7M7OTNYNWGXB47AUYEUAUDC6V4F357",
        "type": "events"
    },{
        "contract": "pair_ARST_AQUA",
        "address": "CAXROB2BP7SIIEHPD52NQKUXFD7M7OTNYNWGXB47AUYEUAUDC6V4F357",
        "type": "entry"
    },{
            "contract": null,
        "address": "GCHR5WWPDFF3U3HP2NA6TI6FCQPYEWS3UOPIPJKZLAAFM57CEG4ZYBWP",
        "type": "account"
    }
]}
```

**Comment by abstract829** [comment]
created a script inside ```suscribe/index.js``` which suscribes to all adresses and events that are indicated in ```suscribe/config.js``` using the following structure:

```bash
const suscriptions = [
  {
    name: "Router",
    address: "CCJRRQE4YNU4475CCUXYFU4PDWNOUQ6V2WQAPZP2Z6LF7SPMY74W7POU",
    events: [CONTRACT_EVENTS],
    params: {},
  },
  {
    name: "Factory",
    address: "CCJRRQE4YNU4475CCUXYFU4PDWNOUQ6V2WQAPZP2Z6LF7SPMY74W7POU",
    events: [CONTRACT_EVENTS],
    params: {},
  },
  {
    name: "Pair0",
    address: "CCJRRQE4YNU4475CCUXYFU4PDWNOUQ6V2WQAPZP2Z6LF7SPMY74W7POU",
    events: [CONTRACT_EVENTS],
    params: {},
  },
  {
    name: "Account0",
    address: "CCJRRQE4YNU4475CCUXYFU4PDWNOUQ6V2WQAPZP2Z6LF7SPMY74W7POU",
    events: [FULL_ACCOUNT],
    params: {},
  },
];
```

I am using config.js instead of .json to use the event types, is it fine or do we need 100% a json file ?

Also need to add to ```suscribe/index.js``` the verification to check if the event has already been suscribed or not

**Comment by chopan123** [comment]
I prefer a json file but I don't have a strong reason so we can keep it as a js. However:
- [x] Change EVENT_TYPES to SUBSCRIPTION_TYPES 
- [x] remove package-lock, use yarn
- [x] fix typo, (it should be subscribe instead of suscribe)
- [x] It is sending data={} (empty) while subscribing
- [x] Fix args when sending different types of subscriptions, for contracts is contractID, but for full accounts it is publickey

Continue development

**Comment by abstract829** [comment]
moved to a json file:

```bash
{
  "suscriptions": [
    {
      "name": "Router",
      "events": ["event"],
      "params": {
        "contract_id": "CCIXZA5YCGAFDCSRNC4PS7OK2DGKIZFRQHBQPJKPHSHKSWXBW445DQU6"
      }
    },
    {
      "name": "Factory",
      "events": ["event"],
      "params": {
        "contract_id": "CDQFXDLV7LLLZJCE3BBID5KFPXZADRKDLURCZ2CQXPPRFEEDRZ6DHY73"
      }
    },
    {
      "name": "Account0",
      "events": ["account"],
      "params": {
        "publickey": "GDKXVNZXCJERWN7FSBOUPE5HKQ62LKYVZZYI4PMZHFVN6IWOFVRVI6LH"
      }
    }
  ]
}
```

params should contain anything you want to pass to the event subscription, i add validation in the script that you are sending the required params

also fixed typo and the other things

about "check that the address with its type have not been subscribed before" i didnt find out how we could do that, and i asked to mercury team and they said that you can subscribe many times and it doesnt matter

**Comment by esteblock** [comment]
@chopan123 por favor revisar
