### ISSUE TITLE
D3.1: Choose the 7 most common DeFi transactions (Which protocol, which type of swap) 

### ISSUE THREAD

**Issue by esteblock** [paltalabs/mercury-client#4]
- Provide Liquidity in AMM (soroswap)
- Remove Liquidity in AMM (soroswap)
- Swap Liquidity in AMM (soroswap)

**Comment by chopan123** [comment]
First iteration:
- Stellar classic
  - sent/receive transfers/payments
- Soroswap
  - Swap
  - Add liquidity
  - Remove Liquidity
- StellarX
  - Swap
  - Add liquidity
  - Remove Liquidity

**Comment by chopan123** [comment]
Second iteration:
- send payment
- received payment
- SDEX liquidity pool deposit
- SDEX liquidity pool withdraw
- SDEX swap
- Path payment Strict send
- Path payment Strict receive
- Soroswap Add Liquidity
- Soroswap Remove Liquidity
- Soroswap Swap

**Comment by chopan123** [comment]
Third iteration:

- send payment
- received payment
- SDEX liquidity pool deposit
- SDEX liquidity pool withdraw
- SDEX Sell Offer
- Path payment Strict send
- Path payment Strict receive
- Soroswap Add Liquidity
- Soroswap Remove Liquidity
- Soroswap Swap

**Comment by esteblock** [comment]
State Today:
-     ✅ send payment
-     ✅ received payment
-     ✅ SDEX liquidity pool deposit
-     ✅ SDEX liquidity pool withdraw
-     👷🏽‍♂️ Soroswap Add Liquidity
-     👷🏽‍♂️ Soroswap Remove Liquidity
-     👷🏽‍♂️ Soroswap Swap


Wont do
-     SDEX Sell Offer
-     Path payment Strict send
-     Path payment Strict receive
