### ISSUE TITLE
Translate to Typescript

### ISSUE THREAD

**Issue by esteblock** [paltalabs/mercury-client#9]

**Comment by abstract829** [comment]
moví todo a ts, excepto la ultima función que agrego @chopan123  en SDEX/addRemoveLiquidity, 

no sé si es código sacado de alguna parte que este disponible en typescript igualmente o si lo creaste tu @chopan123  y hay que tipearlo ? no lo toque para no matar nada

**Comment by chopan123** [comment]
> moví todo a ts, excepto la ultima función que agrego @chopan123 en SDEX/addRemoveLiquidity,
> 
> no sé si es código sacado de alguna parte que este disponible en typescript igualmente o si lo creaste tu @chopan123 y hay que tipearlo ? no lo toque para no matar nada

We will deprecate that script
